// <auto-generated />
namespace event_management_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EventsCodesModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventsCodesModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202210211233128_Events-Codes-Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
